name: sync-longzhuzhu-Script
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-CXK-JavaScript
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.ZYT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync CXK Script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/leecheng310/longzhuzhu.git"
          source_branch: "main"
          destination_branch: "sync-longzhuzhu-JavaScript"
          github_token: ${{ secrets.ZYT }}
